grails-app/domain/kit/VorgangsLog.groovy
package kit



class VorgangsLog {
    Date dateCreated

    Vorgang vorgang
    String text
    String benutzer
    String komplett

    static constraints = {
    }

    static mapping = {
        komplett  sqlType: 'TEXT'
        text  sqlType: 'TEXT'
    }

    String toString(){
        dateCreated.format("dd.MM.yyyy") + " (" + benutzer + ") " + text
    }
}

grails-app/controllers/kit/VorgangsLogController.groovy
package kit

import grails.validation.ValidationException
import org.springframework.security.core.context.SecurityContextHolder

import static org.springframework.http.HttpStatus.*

class VorgangsLogController {

    VorgangsLogService vorgangsLogService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def show(Long id) {
        respond vorgangsLogService.get(id)
    }
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'vorgangsLog.label', default: 'VorgangsLog'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/vorgangsLog/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'vorgangsLog.label', default: 'VorgangsLog')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-vorgangsLog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-vorgangsLog" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.vorgangsLog}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.vorgangsLog}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.vorgangsLog}" method="POST">
                <fieldset class="form">
                    <f:all bean="vorgangsLog"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/vorgangsLog/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'vorgangsLog.label', default: 'VorgangsLog')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-vorgangsLog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-vorgangsLog" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.vorgangsLog}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.vorgangsLog}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.vorgangsLog}" method="PUT">
                <g:hiddenField name="version" value="${this.vorgangsLog?.version}" />
                <fieldset class="form">
                    <f:all bean="vorgangsLog"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/vorgangsLog/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'vorgangsLog.label', default: 'VorgangsLog')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-vorgangsLog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-vorgangsLog" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${vorgangsLogList}" />

            <div class="pagination">
                <g:paginate total="${vorgangsLogCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/vorgangsLog/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'vorgangsLog.label', default: 'VorgangsLog')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-vorgangsLog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-vorgangsLog" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>

            <ol class="property-list vorgangsLog alert alert-info">

                <li class="fieldcontain">
                    <span id="vorgang-label" class="property-label">Vorgang</span>
                    <div class="property-value" aria-labelledby="vorgang-label"><a href="/vorgang/show/${vorgangsLog.vorgang.id}">${vorgangsLog.vorgang}</a></div>
                </li>

                <li class="fieldcontain">
                    <span id="benutzer-label" class="property-label">Benutzer</span>
                    <div class="property-value" aria-labelledby="benutzer-label">${vorgangsLog.benutzer}</div>
                </li>



            </ol>
            <div class="property-list vorgangsLog">

            <h3>Änderungen:</h3>
            <div class="well">

                <div class="property-value" aria-labelledby="komplett-label">
                    ${vorgangsLog.komplett.encodeAsRaw()}
                </div>
            </div>
            </div>
        </div>
    </body>
</html>