grails-app/domain/kit/DateiAnhang.groovy
package kit


import org.hibernate.type.StringNVarcharType
import org.springframework.security.core.context.SecurityContextHolder

class DateiAnhang {

    Date dateCreated
    Date lastUpdated

    String pfad
    String name, beschreibung

    Vorgang vorgang

    long groesse

    static mapping = {
        pfad  sqlType: 'TEXT'
        name  sqlType: 'TEXT'
        beschreibung  widget: 'textarea', nullable: true
    }

    static constraints = {
        beschreibung nullable: true
    }

    String toString() {
        name
    }
}

grails-app/controllers/kit/DateiAnhangController.groovy
package kit

import grails.gorm.transactions.Transactional
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.springframework.security.core.context.SecurityContextHolder

import static org.springframework.http.HttpStatus.*

class DateiAnhangController {

    DateiAnhangService dateiAnhangService
    ImageService imageService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    @Transactional
    def remove(Long id){
        def d = DateiAnhang.get(id)
        def vid = d.vorgang
        vid.removeFromBilder(d)
        vid.save()
        d.delete()
        redirect controller: 'vorgang', action: 'show', id: vid.id
    }



    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    def render(Long id){
        def d = DateiAnhang.get(id)
        if(!d){
            render ""
            return
        }
        render file: imageService.getBytes(d.pfad), fileName: d.name
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond dateiAnhangService.list(params), model:[bildCount: dateiAnhangService.count()]
    }

    def show(Long id) {
        respond dateiAnhangService.get(id)
    }

    def create() {
        respond new DateiAnhang(params)
    }

    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    def save(DateiAnhang bild) {
        if (bild == null) {
            notFound()
            return
        }

        try {
            dateiAnhangService.save(bild)
            bild.vorgang.addToBilder(bild)
            bild.vorgang.save()
        } catch (ValidationException e) {
            respond bild.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'dateiAnhang.label', default: 'DateiAnhang'), bild.id])
                redirect bild
            }
            '*' { respond bild, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond dateiAnhangService.get(id)
    }

    def update(DateiAnhang bild) {
        if (bild == null) {
            notFound()
            return
        }

        try {
            dateiAnhangService.save(bild)
        } catch (ValidationException e) {
            respond bild.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'dateiAnhang.label', default: 'DateiAnhang'), bild.id])
                redirect bild
            }
            '*'{ respond bild, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        dateiAnhangService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'dateiAnhang.label', default: 'DateiAnhang'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'dateiAnhang.label', default: 'DateiAnhang'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/dateiAnhang/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dateiAnhang.label', default: 'DateiAnhang')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-dateiAnhang" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-dateiAnhang" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.dateiAnhang}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.dateiAnhang}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.dateiAnhang}" method="POST">
                <fieldset class="form">
                    <f:all bean="dateiAnhang"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/dateiAnhang/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dateiAnhang.label', default: 'DateiAnhang')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-dateiAnhang" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-dateiAnhang" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.dateiAnhang}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.dateiAnhang}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.dateiAnhang}" method="PUT">
                <g:hiddenField name="version" value="${this.dateiAnhang?.version}" />
                <fieldset class="form">
                    <f:all bean="dateiAnhang"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/dateiAnhang/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dateiAnhang.label', default: 'DateiAnhang')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-dateiAnhang" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-dateiAnhang" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${dateiAnhangList}" />

            <div class="pagination">
                <g:paginate total="${dateiAnhangCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/dateiAnhang/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dateiAnhang.label', default: 'DateiAnhang')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-dateiAnhang" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}">Startseite</a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-dateiAnhang" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="dateiAnhang" />
            <g:form resource="${this.dateiAnhang}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.dateiAnhang}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>